title: Ajouter une section enveloppée avec des éléments de largeur normale
hero_image: images/banner.png
description: Ajoute une section enveloppée avec des éléments de largeur normale
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ajouter une section enveloppée avec des éléments de largeur normale
